// <auto-generated />
namespace Prose.Infrastructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class fix_maxlength_password_unique_username : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fix_maxlength_password_unique_username));
        
        string IMigrationMetadata.Id
        {
            get { return "202206111602444_fix_maxlength_password_unique_username"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
