// <auto-generated />
namespace Prose.Infrastructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class ProseV1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ProseV1));
        
        string IMigrationMetadata.Id
        {
            get { return "202206102229147_ProseV1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
